#!/usr/local/bin/python3
# Copyright (c) KMG. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
##

# List of column names
ID = "ID"
HEADER = "Header"
TYPE = "Type"
CONNECTIONS = "Connections"
MAX_CONNECTIONS = "MaxConnections"
STORAGE = "Storage"
ACTION = "Action"
LATENCY_TIME_UNIT = "LatencyTimeUnit"
WRITERS = "Writers"
READERS = "Readers"
MAX_WRITERS= "MaxWriters"
MAX_READERS = "MaxReaders"
WRITE_REQUEST_MB= "WriteRequestMB"
READ_REQUEST_MB= "ReadRequestMB"
WRITE_REQUEST_RECORDS= "WriteRequestRecords"
READ_REQUEST_RECORDS= "ReadRequestRecords"
MB_PER_SEC = "MB/Sec"
WRITE_REQUEST_MB_PER_SEC = "WriteRequestMB/Sec"
READ_REQUEST_MB_PER_SEC = "ReadRequestMB/Sec"
RECORDS_PER_SEC = "Records/Sec"
WRITE_REQUEST_RECORDS_PER_SEC = "WriteRequestRecords/Sec"
READ_REQUEST_RECORDS_PER_SEC = "ReadRequestRecords/Sec"
WRITE_TIMEOUT_EVENTS = "WriteTimeoutEvents"
WRITE_TIMEOUT_EVENTS_PER_SEC = "WriteTimeoutEventsPerSec"
READ_TIMEOUT_EVENTS = "ReadTimeoutEvents"
READ_TIMEOUT_EVENTS_PER_SEC = "ReadTimeoutEventsPerSec"
WRITE_READ_REQUEST_PENDING_MB = "WriteReadRequestPendingMB"
WRITE_READ_REQUEST_PENDING_RECORDS = "WriteReadRequestPendingRecords"
MB = "MB"
RECORDS = "Records"
WRITE_RESPONSE_PENDING_MB = "WriteResponsePendingMB"
WRITE_RESPONSE_PENDING_RECORDS = "WriteResponsePendingRecords"
READ_RESPONSE_PENDING_MB = "ReadResponsePendingMB"
READ_RESPONSE_PENDING_RECORDS = "ReadResponsePendingRecords"
AVG_LATENCY = "AvgLatency"
MIN_LATENCY = "MinLatency"
MAX_LATENCY = "MaxLatency"

# Percentile columns
PERCENTILE_1 = "Percentile_1"
PERCENTILE_5 = "Percentile_5"
PERCENTILE_10 = "Percentile_10"
PERCENTILE_15 = "Percentile_15"
PERCENTILE_20 = "Percentile_20"
PERCENTILE_25 = "Percentile_25"
PERCENTILE_30 = "Percentile_30"
PERCENTILE_35 = "Percentile_35"
PERCENTILE_40 = "Percentile_40"
PERCENTILE_45 = "Percentile_45"
PERCENTILE_50 = "Percentile_50"
PERCENTILE_55 = "Percentile_55"
PERCENTILE_60 = "Percentile_60"
PERCENTILE_65 = "Percentile_65"
PERCENTILE_70 = "Percentile_70"
PERCENTILE_75 = "Percentile_75"
PERCENTILE_80 = "Percentile_80"
PERCENTILE_85 = "Percentile_85"
PERCENTILE_90 = "Percentile_90"
PERCENTILE_92_5 = "Percentile_92.5"
PERCENTILE_95 = "Percentile_95"
PERCENTILE_97_5 = "Percentile_97.5"
PERCENTILE_99 = "Percentile_99"
PERCENTILE_99_25 = "Percentile_99.25"
PERCENTILE_99_5 = "Percentile_99.5"
PERCENTILE_99_75 = "Percentile_99.75"
PERCENTILE_99_9 = "Percentile_99.9"
PERCENTILE_99_95 = "Percentile_99.95"
PERCENTILE_99_99 = "Percentile_99.99"

# Percentile count columns
PERCENTILE_COUNT_1 = "Percentile_Count_1"
PERCENTILE_COUNT_5 = "Percentile_Count_5"
PERCENTILE_COUNT_10 = "Percentile_Count_10"
PERCENTILE_COUNT_15 = "Percentile_Count_15"
PERCENTILE_COUNT_20 = "Percentile_Count_20"
PERCENTILE_COUNT_25 = "Percentile_Count_25"
PERCENTILE_COUNT_30 = "Percentile_Count_30"
PERCENTILE_COUNT_35 = "Percentile_Count_35"
PERCENTILE_COUNT_40 = "Percentile_Count_40"
PERCENTILE_COUNT_45 = "Percentile_Count_45"
PERCENTILE_COUNT_50 = "Percentile_Count_50"
PERCENTILE_COUNT_55 = "Percentile_Count_55"
PERCENTILE_COUNT_60 = "Percentile_Count_60"
PERCENTILE_COUNT_65 = "Percentile_Count_65"
PERCENTILE_COUNT_70 = "Percentile_Count_70"
PERCENTILE_COUNT_75 = "Percentile_Count_75"
PERCENTILE_COUNT_80 = "Percentile_Count_80"
PERCENTILE_COUNT_85 = "Percentile_Count_85"
PERCENTILE_COUNT_90 = "Percentile_Count_90"
PERCENTILE_COUNT_92_5 = "Percentile_Count_92_5"
PERCENTILE_COUNT_95 = "Percentile_Count_95"
PERCENTILE_COUNT_97_5 = "Percentile_Count_97_5"
PERCENTILE_COUNT_99 = "Percentile_Count_99"
PERCENTILE_COUNT_99_25 = "Percentile_Count_99.25"
PERCENTILE_COUNT_99_5 = "Percentile_Count_99.5"
PERCENTILE_COUNT_99_75 = "Percentile_Count_99.75"
PERCENTILE_COUNT_99_9 = "Percentile_Count_99.9"
PERCENTILE_COUNT_99_95 = "Percentile_Count_99.95"
PERCENTILE_COUNT_99_99 = "Percentile_Count_99.99"


